# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/tlu_event_fifo/tlu_event_fifo.xci
# IP: The module: 'tlu_event_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/tlu_event_fifo/tlu_event_fifo/tlu_event_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'tlu_event_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/tlu_event_fifo/tlu_event_fifo/tlu_event_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tlu_event_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/tlu_event_fifo/tlu_event_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tlu_event_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/tlu_event_fifo/tlu_event_fifo.xci
# IP: The module: 'tlu_event_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/tlu_event_fifo/tlu_event_fifo/tlu_event_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'tlu_event_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/tlu_event_fifo/tlu_event_fifo/tlu_event_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'tlu_event_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/tlu_event_fifo/tlu_event_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tlu_event_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
