# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.cache/wt [current_project]
set_property parent.project_path /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/temac_gbe_v9_rgmii.dcp
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/temac_gbe_v9_rgmii.dcp]
add_files -quiet /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4.dcp
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4.dcp]
read_vhdl -library work {
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/ipbus_package.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/ipbus_trans_decl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/transactor_if.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/transactor_sm.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/transactor_cfg.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_tx_mux.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_build_ping.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_status_buffer.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_txtransactor_if_simple.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_dualportram_rx.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_clock_crossing_if.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_build_resend.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_do_rx_reset.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_rarp_block.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_buffer_selector.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_dualportram_tx.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_rxtransactor_if_simple.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_build_arp.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_build_payload.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_packet_parser.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_build_status.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_rxram_mux.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_dualportram.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_rxram_shim.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_byte_sum.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_ipaddr_block.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/dtype.vhdl
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/emac_hostbus_decl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/trans_arb.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/ipbus_clock_div.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/transactor.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/udp_if_flat.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/i2c/i2c_master_registers.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/i2c/i2c_master_bit_ctrl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/i2c/i2c_master_byte_ctrl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/fmcTLU_pkg.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/delay.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_ctrl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/led_stretcher.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/eth_7s_rgmii.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/clocks_7s_extphy_se.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/imports/hdl/ipbus_reg_types.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/i2c/i2c_master_top.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/ipbus_decode_tlu.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/fmcTLU_pkg_body.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/Dummy_DUT.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/ipbus_fabric_sel.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/enclustra_ax3_pm3_infra.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ctrlreg_v.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/logic_clocks_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/i2c/i2c_master_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/hdl/top_EUDET_dummy.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc -unmanaged /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/constraints/enclustra_ax3_pm3.tcl
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/constraints/enclustra_ax3_pm3.tcl]

read_xdc /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/constraints/I2C_constr.xdc
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/constraints/I2C_constr.xdc]

read_xdc /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/constraints/EUDET_dummy_constr.xdc
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/constraints/EUDET_dummy_constr.xdc]


synth_design -top top_EUDET_dummy -part xc7a35tcsg324-1


write_checkpoint -force -noxdef top_EUDET_dummy.dcp

catch { report_utilization -file top_EUDET_dummy_utilization_synth.rpt -pb top_EUDET_dummy_utilization_synth.pb }
