# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/temac_gbe_v9_rgmii.xci
# IP: The module: 'temac_gbe_v9_rgmii' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/synth/temac_gbe_v9_rgmii_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_rgmii'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/synth/temac_gbe_v9_rgmii.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/synth/temac_gbe_v9_rgmii_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/synth/temac_gbe_v9_rgmii_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/temac_gbe_v9_rgmii.xci
# IP: The module: 'temac_gbe_v9_rgmii' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/synth/temac_gbe_v9_rgmii_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/synth/temac_gbe_v9_rgmii.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/synth/temac_gbe_v9_rgmii_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/work/EUDET_dummy.srcs/sources_1/ip/temac_gbe_v9_rgmii/synth/temac_gbe_v9_rgmii_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'temac_gbe_v9_rgmii'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
