# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.cache/wt [current_project]
set_property parent.project_path /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/tlu_event_fifo/tlu_event_fifo.dcp
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/tlu_event_fifo/tlu_event_fifo.dcp]
add_files -quiet /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/internalTriggerGenerator/internalTriggerGenerator.dcp
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/internalTriggerGenerator/internalTriggerGenerator.dcp]
add_files -quiet /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4.dcp
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/mac_fifo_axi4/mac_fifo_axi4.dcp]
add_files -quiet /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/temac_gbe_v9_rgmii/temac_gbe_v9_rgmii.dcp
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/temac_gbe_v9_rgmii/temac_gbe_v9_rgmii.dcp]
read_vhdl -library work {
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_trans_decl.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_package.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_sm.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_cfg.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor_if.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/fmcTLU_pkg.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_tx_mux.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_ping.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_status_buffer.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_txtransactor_if_simple.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram_rx.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_clock_crossing_if.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_resend.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_do_rx_reset.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rarp_block.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_buffer_selector.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram_tx.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxtransactor_if_simple.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_arp.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_payload.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_packet_parser.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_build_status.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxram_mux.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_dualportram.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_rxram_shim.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_byte_sum.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_ipaddr_block.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_util/firmware/hdl/ipbus_clock_div.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/udp_if_flat.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_eth/firmware/hdl/emac_hostbus_decl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/fmcTLU_pkg_body.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/i2c/i2c_master_registers.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/i2c/i2c_master_byte_ctrl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/i2c/i2c_master_bit_ctrl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/single_pulse_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/counterWithReset_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/trigger/IODELAYCal_FSM_rtl.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_reg_types.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/trans_arb.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/transactor.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/synchronizeRegisters_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/stretchPulse_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/pulseClockDomainCrossing_rtl.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_slaves/firmware/hdl/ipbus_ctrlreg_v.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/i2c/i2c_master_top.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/coincidenceLogic_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/led_stretcher.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/dut/DUTInterface_AIDA_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/clocks/clocks_7s_extphy_se.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/trigger/arrivalTimeLUT_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/dut/DUTInterface_EUDET_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/eth_7s_rgmii.vhd
  /users/phpgb/ipbus-firmware/components/ipbus_core/firmware/hdl/ipbus_ctrl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/ipbus_decode_tlu.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/T0_Shutter_Iface_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/logic_clocks_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/ipbus_fabric_sel.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/i2c/i2c_master_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/eventBuffer_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/enclustra_ax3_pm3_infra.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/dut/DUTInterfaces_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/trigger/triggerInputs_newTLU_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/top_enclustra_tlu_v1e.vhd
}
read_vhdl -vhdl2008 -library work {
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/trigger/dualSERDES_1to4_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/eventFormatter_rtl.vhd
  /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/hdl/trigger/triggerLogic_rtl.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc -unmanaged /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/constraints/enclustra_ax3_pm3.tcl
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/constraints/enclustra_ax3_pm3.tcl]

read_xdc /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/constraints/I2C_constr.xdc
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/constraints/I2C_constr.xdc]

read_xdc /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/constraints/TLU_enclustra_v1e.xdc
set_property used_in_implementation false [get_files /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/constraints/TLU_enclustra_v1e.xdc]


synth_design -top top_tlu_v1e -part xc7a35tcsg324-1 -flatten_hierarchy none


write_checkpoint -force -noxdef top_tlu_v1e.dcp

catch { report_utilization -file top_tlu_v1e_utilization_synth.rpt -pb top_tlu_v1e_utilization_synth.pb }
