# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/internalTriggerGenerator/internalTriggerGenerator.xci
# IP: The module: 'internalTriggerGenerator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/internalTriggerGenerator/internalTriggerGenerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'internalTriggerGenerator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/internalTriggerGenerator/internalTriggerGenerator.xci
# IP: The module: 'internalTriggerGenerator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /users/phpgb/workspace/myFirmware/AIDA/TLU_v1e/work/TLU_v1e.srcs/sources_1/ip/internalTriggerGenerator/internalTriggerGenerator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'internalTriggerGenerator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
