set_property SRC_FILE_INFO {cfile:/users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/constraints/enclustra_ax3_pm3.tcl rfile:../../../../constraints/enclustra_ax3_pm3.tcl id:1 unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:/users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/constraints/I2C_constr.xdc rfile:../../../../constraints/I2C_constr.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/users/phpgb/workspace/myFirmware/AIDA/EUDETdummy/constraints/EUDET_dummy_constr.xdc rfile:../../../../constraints/EUDET_dummy_constr.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN P17 [get_ports clk_enclustra]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN M16 [get_ports {leds[0]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN M17 [get_ports {leds[1]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN L18 [get_ports {leds[2]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN M18 [get_ports {leds[3]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports {rgmii_txd[0]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN T18 [get_ports {rgmii_txd[1]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports {rgmii_txd[2]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports {rgmii_txd[3]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN T16 [get_ports {rgmii_tx_ctl}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports {rgmii_txc}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {rgmii_rxd[0]}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {rgmii_rxd[1]}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN V15 [get_ports {rgmii_rxd[2]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {rgmii_rxd[3]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN R16 [get_ports {rgmii_rx_ctl}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports {rgmii_rxc}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:NONE read:READ} [current_design]
set_property PACKAGE_PIN M13 [get_ports {phy_rstn}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C2 [get_ports i2c_reset]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N17 [get_ports i2c_scl_b]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P18 [get_ports i2c_sda_b]
set_property src_info {type:XDC file:3 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C1 [get_ports clk_gen_rst]
set_property src_info {type:XDC file:3 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F6 [get_ports gpio]
set_property src_info {type:XDC file:3 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports sysclk_40_i_p]
set_property src_info {type:XDC file:3 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T4 [get_ports sysclk_40_i_n]
set_property src_info {type:XDC file:3 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports sysclk_50_o_p]
set_property src_info {type:XDC file:3 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D3 [get_ports sysclk_50_o_n]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R7 [get_ports {busy_o[0]}]
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {busy_o[1]}]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R8 [get_ports {busy_o[2]}]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K5 [get_ports {busy_o[3]}]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R6 [get_ports {triggers_o[0]}]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P2 [get_ports {triggers_o[1]}]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R1 [get_ports {triggers_o[2]}]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U1 [get_ports {triggers_o[3]}]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N5 [get_ports {cont_o[0]}]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P4 [get_ports {cont_o[1]}]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M6 [get_ports {cont_o[2]}]
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L6 [get_ports {cont_o[3]}]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L1 [get_ports {spare_o[0]}]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M4 [get_ports {spare_o[1]}]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N2 [get_ports {spare_o[2]}]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M3 [get_ports {spare_o[3]}]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K3 [get_ports {dut_clk_o[0]}]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F4 [get_ports {dut_clk_o[1]}]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E2 [get_ports {dut_clk_o[2]}]
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G4 [get_ports {dut_clk_o[3]}]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P5 [get_ports {cont_i[0]}]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P3 [get_ports {cont_i[1]}]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N6 [get_ports {cont_i[2]}]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L5 [get_ports {cont_i[3]}]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M1 [get_ports {spare_i[0]}]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N4 [get_ports {spare_i[1]}]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N1 [get_ports {spare_i[2]}]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M2 [get_ports {spare_i[3]}]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R5 [get_ports {triggers_i[0]}]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports {triggers_i[1]}]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T1 [get_ports {triggers_i[2]}]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V1 [get_ports {triggers_i[3]}]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T6 [get_ports {busy_i[0]}]
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports {busy_i[1]}]
set_property src_info {type:XDC file:3 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T8 [get_ports {busy_i[2]}]
set_property src_info {type:XDC file:3 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L4 [get_ports {busy_i[3]}]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L3 [get_ports {dut_clk_i[0]}]
set_property src_info {type:XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F3 [get_ports {dut_clk_i[1]}]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D2 [get_ports {dut_clk_i[2]}]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G3 [get_ports {dut_clk_i[3]}]
